//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sobaki.Data.Remote
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dog
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Dog()
        {
            this.DeadDogs = new HashSet<DeadDog>();
            this.GivenDogs = new HashSet<GivenDog>();
            this.Receptions = new HashSet<Reception>();
        }
    
        public int Id { get; set; }
        public int Number { get; set; }
        public int Height { get; set; }
        public int Weight { get; set; }
        public int GenderId { get; set; }
        public int Age { get; set; }
        public int Phone { get; set; }
        public byte[] BinImage { get; set; }
        public int CageId { get; set; }
        public System.DateTime Timestamp { get; set; }
        public int BreedId { get; set; }
    
        public virtual Breed Breed { get; set; }
        public virtual Cage Cage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeadDog> DeadDogs { get; set; }
        public virtual Gender Gender { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GivenDog> GivenDogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reception> Receptions { get; set; }
    }
}
