//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sobaki.Data.Remote
{
    using System;
    using System.Collections.Generic;
    
    public partial class GivenDog
    {
        public int Id { get; set; }
        public int DogId { get; set; }
        public System.DateTime Timestamp { get; set; }
    
        public virtual Dog Dog { get; set; }
    }
}
